lanuage: python
python:
  - "3.8"

sudo: required

env:
  matrix:
  - OS_TYPE=fedora OS_VERSION=32
  
services:
  - docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  