---
language: python
python: 
  - "3.6"

env:
  - CONTAINER_ID=$(mktemp)

services: 
  - docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 
 # Customize containers
  - sudo docker build --rm=true --file=tests/Dockerfile.centos --tag=centos:ansible .


script:
  # Test building Dockerfile.
  - docker build -t docker-ansible .

  # Test running the container.
  - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

  # Verify Ansible is available in the container.
  - docker exec --tty test-container env TERM=xterm ansible --version


notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/