lanuage: python
python:
  - "3.8"

sudo: required

env:
  matrix:
  - OS_TYPE=fedora OS_VERSION=32
  
services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  