lanuage: python
python:
  - "3.8"

sudo: required

env:
  - CONTAINER_ID=$(mktemp)
  
services:
  - docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  # Pull containers
  - sudo docker pull manjarolinux/base

  # Customize containers
  - sudo docker build --rm=true --file=tests/Dockerfile.manjaro --tag=manjaro:ansible .

  script:

  notifications:
    