lanuage: python
python:
  - "3.8"

virtualenv:
  system_site_packages: true

sudo: required

env:
  - CONTAINER_ID=$(mktemp)
  
services:
  - docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  # Pull containers
  - sudo docker pull fedora:32

  # Customize containers
  - sudo docker build --rm=true --file=tests/Dockerfile.centos --tag=centos:ansible .

  script:

  notifications:
    