---
language: python
python: 
  - "3.6"

sudo: required
env:
  - CONTAINER_ID=$(mktemp)

services: 
  - docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 
script:

 # Customize containers
  - sudo docker build --rm=true --file=tests/Dockerfile.centos --tag=centos:ansible .
  

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/