---
#  ████████╗ █████╗ ███████╗██╗  ██╗
#  ╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
#     ██║   ███████║███████╗█████╔╝ 
#     ██║   ██╔══██║╚════██║██╔═██╗ 
#     ██║   ██║  ██║███████║██║  ██╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#

# -----------------------------------------------------------------------------
# When working with multiple OSes, inevitably there will be packages, 
# configuration files and service calls that are vastly different than one
# another. There can even be instances in which sub-versions of OSes can have 
# major differences.
# 
# This method pulls in variables based on the client's OS and uses those 
# variables to that machine's needs.
# -----------------------------------------------------------------------------
#
- name: Load OS dependent variables.
  include_vars: '{{ item_os }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution | lower}}_{{ ansible_distribution_major_version | lower}}.yml'
      - '{{ ansible_distribution | lower}}.yml'
      - '{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version | lower }}.yml'
      skip: false
  loop_control:
    loop_var: item_os
  tags: [ 'OS dependency']

# -----------------------------------------------------------------------------
# assert - Asserts given expressions are true
# -----------------------------------------------------------------------------
#
- name: OS is supported.
  assert:
    that: os_supported == True
  tags: [ 'OS dependency']

# -----------------------------------------------------------------------------
# include - Include play or task list(s)
# -----------------------------------------------------------------------------
#
# Load 'os_{{ ansible_os_family }}.yml' task file
- include: 'os_{{ ansible_os_family | lower }}.yml'
  
# Load 'systemd-install.yml' task file
- include: 'systemd-install.yml'

# Load 'systemd-config.yml' task file
- include: 'systemd-config.yml'

# Load 'systemd-service.yml' task file
- include: 'systemd-service.yml'

# Load 'systemd-symlinks' task file
- include: 'systemd-symlinks.yml'

# Load 'systemd-sysctl.yml' task file
- include: 'systemd-sysctl.yml'
  when: 
    - systemd_networks is defined
    - systemd_networks is not none

# Load 'cleanup.yml' task file
- include: 'cleanup.yml'
