---
#  ████████╗ █████╗ ███████╗██╗  ██╗
#  ╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
#     ██║   ███████║███████╗█████╔╝ 
#     ██║   ██╔══██║╚════██║██╔═██╗ 
#     ██║   ██║  ██║███████║██║  ██╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#

# -----------------------------------------------------------------------------
# When working with multiple OSes, inevitably there will be packages, 
# configuration files and service calls that are vastly different than one
# another. There can even be instances in which sub-versions of OSes can have 
# major differences.
# 
# This method pulls in variables based on the client's OS and uses those 
# variables to that machine's needs.
# -----------------------------------------------------------------------------
#
- name: Load OS dependent variables
  include_vars: '{{ item_os }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution | lower}}_{{ ansible_distribution_major_version | lower}}.yml'
      - '{{ ansible_distribution | lower}}.yml'
      - '{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version | lower }}.yml'
      skip: false
  loop_control:
    loop_var: item_os
  tags: [ 'OS dependency']

# Load '{{ ansible_os_family }}-install.yml' task file
- include: '{{ ansible_os_family | lower }}-install.yml'
  
# Load 'install-systemd.yml' task file
- include: 'install-systemd.yml'

# Load 'config-systemd.yml' task file
- include: 'config-systemd.yml'

# Load 'sysctl-systemd.yml' task file
- include: 'sysctl-systemd.yml'
  when: 
    - systemd_networks is defined
    - systemd_networks is not none

# Load 'service-systemd.yml' task file
- include: 'service-systemd.yml'

# Load 'symlinks-systemd.yml' task file
- include: 'symlinks-systemd.yml'

# Load 'cleanup.yml' task file
- include: 'cleanup.yml'
