---
#  ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗            
#  ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║            
#  ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║█████╗      
#  ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║╚════╝      
#  ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗       
#  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝       
#                                                              
#  ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗██████╗ 
#  ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║██╔══██╗
#  ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║██║  ██║
#  ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║██║  ██║
#  ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║██████╔╝
#  ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝╚═════╝ 
#

# -----------------------------------------------------------------------------
# package - Generic OS package manager.
# Installs packages using the underlying OS package manager. It is registering 
# the result of the task. The until value applies the conditional. In this case
# it keeps running the task until the 'install_packages' is a success.
# The delay is how much time to wait between retries.
# -----------------------------------------------------------------------------
#
- name: systemd-install | Ensure that the systemd packages are installed on host.
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ systemd_networkd_base_pkgs }}'
  when:
    - systemd_networkd_base_pkgs |  length > 0 
  register: install_packages
  until: install_packages is success
  retries: 3
  delay: 2
  tags: 
    - install-systemd
    - systemd-networkd

# -----------------------------------------------------------------------------
# file - Manage files and file properties.
# Create a directory if it does not exist and change file/directory ownership,
# group and permissions (equivalent to 0755).
# -----------------------------------------------------------------------------
#
- name: systemd-install | Create systemd-networkd directory.
  file:
    path: '/etc/systemd/network'
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags: 
    - install-systemd
    - systemd-networkd
    - create directory

# -----------------------------------------------------------------------------
# find - Return a list of files based on specific criteria.
# The pattern restrict the list of files to be returned. Multiple patterns can
# be specified and below find files ending with .netdev, .link and .network only
# when the defaults variable with the name 'defaults_systemd_interface_cleanup'
# has the boolean value 'True'.
# -----------------------------------------------------------------------------
#
- name: systemd-install | Find prefixed link, netdev and network files.
  find:
    paths: '/etc/systemd/network'
    patterns: '*.netdev,*.network,*.link'
  register: networkd_files
  when:
    - defaults_systemd_interface_cleanup | bool
  tags: 
    - install-systemd
    - systemd-networkd
    - find files

# -----------------------------------------------------------------------------
# file - Manage files and file properties.
# Files or symlinks will be unlinked that are listed under the variable 
# 'networkd_files' if the defaults variable 'defaults_systemd_interface_cleanup'
# has the boolean value 'True'.
# -----------------------------------------------------------------------------
#
- name: systemd-install | Remove prefixed network files.
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ networkd_files.files }}'
  when:
    - defaults_systemd_interface_cleanup | bool
    - systemd_networks is defined
    - systemd_networks is iterable
    - systemd_networks is not string
  tags: 
    - install-systemd
    - systemd-networkd
    - remove files
