---
#  ███████╗██╗   ██╗███╗   ███╗██╗     ██╗███╗   ██╗██╗  ██╗███████╗      
#  ██╔════╝╚██╗ ██╔╝████╗ ████║██║     ██║████╗  ██║██║ ██╔╝██╔════╝      
#  ███████╗ ╚████╔╝ ██╔████╔██║██║     ██║██╔██╗ ██║█████╔╝ ███████╗█████╗
#  ╚════██║  ╚██╔╝  ██║╚██╔╝██║██║     ██║██║╚██╗██║██╔═██╗ ╚════██║╚════╝
#  ███████║   ██║   ██║ ╚═╝ ██║███████╗██║██║ ╚████║██║  ██╗███████║      
#  ╚══════╝   ╚═╝   ╚═╝     ╚═╝╚══════╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝      
#                                                                         
#  ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗██████╗           
#  ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║██╔══██╗          
#  ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║██║  ██║          
#  ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║██║  ██║          
#  ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║██████╔╝          
#  ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝╚═════╝           
#  

# -----------------------------------------------------------------------------
# file - Manage files and file properties.
# Based the boolean value from defaults variable 
# 'defaults_systemd_resolved_available' that it creates or remove a symlink 
# for resolv.conf.
# -----------------------------------------------------------------------------
# 
- name: systemd-symlinks | Make a symlink for resolv.conf to use systemd-resolved
  file:
    dest: '/etc/resolv.conf'
    src: '/run/systemd/resolve/resolv.conf'
    state: '{{ defaults_systemd_resolved_available 
              | bool
              | default(false)
              | ternary( "link", "absent" ) }}'
    force: yes
  when:
    - systemd_resolved is defined
    - systemd_resolved is not none
    - systemd_resolved | length > 0
  tags:
    - symlinks-systemd
    - systemd-resolved