---
#  ███████╗███████╗██████╗ ██╗   ██╗██╗ ██████╗███████╗         
#  ██╔════╝██╔════╝██╔══██╗██║   ██║██║██╔════╝██╔════╝         
#  ███████╗█████╗  ██████╔╝██║   ██║██║██║     █████╗█████╗     
#  ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██║██║     ██╔══╝╚════╝     
#  ███████║███████╗██║  ██║ ╚████╔╝ ██║╚██████╗███████╗         
#  ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝ ╚═════╝╚══════╝         
#                                                              
#  ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗██████╗ 
#  ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║██╔══██╗
#  ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║██║  ██║
#  ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║██║  ██║
#  ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║██████╔╝
#  ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝╚═════╝ 
#

# -----------------------------------------------------------------------------
# systemd - Manage services
# Enable/disable the service and make sure the service is running or stopped
# depending the defaults variable 'defaults_systemd_run_networkd' boolean value.
# -----------------------------------------------------------------------------
#
- name: systemd-service | Enable and start systemd-networkd, if not running.
  systemd:
    name: 'systemd-networkd'
    enabled: '{{ defaults_systemd_run_networkd 
              | bool
              | default(false)
              | ternary( True, False ) }}'
    state: '{{ defaults_systemd_run_networkd 
              | bool 
              | default(false) 
              | ternary( "started", "stopped" ) }}'
  async: 45
  poll: 0
  when:
    - systemd_networks is defined
    - systemd_networks is not none
  tags:
    - service-systemd
    - systemd-networkd
    - manage

# -----------------------------------------------------------------------------
# wait_for_connection - Waits until remote system is reachable/usable
# Wait 30 seconds for target connection to become reachable/usable
# but only start after 5 seconds. The maximum number to wait for is 60 seconds.
# -----------------------------------------------------------------------------
- name: systemd-service | Wait 60 seconds for target connection.
  wait_for_connection:
    connect_timeout: 60
    sleep: 5
    delay: 5
    timeout: 30

# -----------------------------------------------------------------------------
# systemd - Manage services
# Enable/disable the service and make sure the service is running or stopped
# depending the variable 'defaults_systemd_resolved_available' boolean value.
# -----------------------------------------------------------------------------
#
- name: systemd-service | Enable and start systemd-resolved, if not running.
  systemd:
    name: 'systemd-resolved'
    enabled: '{{ defaults_systemd_resolved_available 
              | bool
              | default(false)
              | ternary( True, False ) }}'
    state: '{{ defaults_systemd_resolved_available 
              | bool 
              | default(false) 
              | ternary( "started", "stopped" ) }}'
  async: 45
  poll: 0
  when:
    - systemd_resolved is defined
    - systemd_resolved is not none
  tags:
    - service-systemd
    - systemd-networkd
    - manage

# -----------------------------------------------------------------------------
# meta - Execute Ansible ‘actions’
# 'flush_handlers' makes Ansible run any handler tasks which have thus far been
#  notified. Ansible inserts these tasks internally at certain points to 
# implicitly trigger handler runs (after pre/post tasks, the final role 
# execution, and the main tasks section of your plays).
# -----------------------------------------------------------------------------
#
- name: systemd-service | Restart systemd_networkd prior to applying sysctl changes.
  meta: flush_handlers
  tags:
    - service-systemd
    - systemd-networkd
    - execute

