FROM centos:7

# Install systemd -- See https://hub.docker.com/_/centos/
RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
RUN yum -y update; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Install Ansible
RUN yum -y install epel-release
RUN yum -y install git ansible sudo
RUN yum clean all

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers
RUN sed -i 's/^\#inventory .*/inventory       = \/etc\/ansible\/host/' /etc/ansible/ansible.cfg
RUN sed -i 's/^\#roles_path .*/roles_path        = \/etc\/ansible\/roles/' /etc/ansible/ansible.cfg

# Install Ansible inventory file
COPY tests/inventory /etc/ansible/hosts
COPY tests/test.yml /etc/ansible/test.yml
COPY tests/requirements.yml /etc/ansible/requirements.yml
RUN ansible-galaxy install -f -r /etc/ansible/requirements.yml
RUN cat /etc/ansible/ansible.cfg

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]