FROM centos:8

# Install systemd -- See https://hub.docker.com/_/centos/
RUN dnf -y swap -- remove fakesystemd -- install systemd systemd-libs
RUN dnf -y update; dnf clean all

# Install Ansible
RUN dnf -y install epel-release
RUN dnf -y install git ansible sudo
RUN dnf clean all

RUN cat /etc/redhat-release
