---
#  ██╗  ██╗ █████╗ ███╗   ██╗██████╗ ██╗     ███████╗██████╗ ███████╗
#  ██║  ██║██╔══██╗████╗  ██║██╔══██╗██║     ██╔════╝██╔══██╗██╔════╝
#  ███████║███████║██╔██╗ ██║██║  ██║██║     █████╗  ██████╔╝███████╗
#  ██╔══██║██╔══██║██║╚██╗██║██║  ██║██║     ██╔══╝  ██╔══██╗╚════██║
#  ██║  ██║██║  ██║██║ ╚████║██████╔╝███████╗███████╗██║  ██║███████║
#  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝
#

# -----------------------------------------------------------------------------
# systemd - Manage services
# Enable the service and restart service 'systemd-networkd' on machine when the
# defaults variable 'defaults_systemd_run_networkd' is set with the boolean
# value 'True'.
# -----------------------------------------------------------------------------
#
- name: Restart systemd-networkd
  systemd:
    name: 'systemd-networkd'
    state: restarted
    enabled: True
  async: 45
  poll: 0
  when:
    - defaults_systemd_run_networkd | bool
  listen: Restart systemd-networkd
  tags: 
    - handlers
    - systemd-networkd

# -----------------------------------------------------------------------------
# systemd - Manage services
# Enable the service and restart service 'systemd-resolved' on machine when the
# defaults variable 'defaults_systemd_resolved_available ' is set with the 
# boolean value 'True'.
# -----------------------------------------------------------------------------
#
- name: Restart systemd-resolved
  systemd:
    name: 'systemd-resolved'
    state: restarted
    enabled: True
  when:
    - defaults_systemd_resolved_available | bool
  tags: 
    - handlers
    - systemd-resolved